name: Football
version: 1.0.0
main: de.dercoder.football.bukkit.FootballPlugin
author: DerCoder
api-version: 1.16.1

commands:
  football:
    description: Provides all interaction opportunities of the football system.
    permission: football.command

permissions:
  football.*:
    description: "Gives you access to all of the football system"
    default: op